version: "3"

services:
  wifiqr:
    # Use nginx directly as the build is served via volume
    image: nginx:stable-alpine
    container_name: "wifiqr"
    restart: unless-stopped
    ports:
      - "9000:80"
    volumes:
      - ./build:/usr/share/nginx/html:ro
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 100m
